// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

import { UserType } from './auth';

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export interface ResponseData<T> {
  data: T[]; // The actual array of jobs
  success: boolean;
  message: string | null;
  meta: Meta;
}

export type Meta = {
  totalPages: number;
  totalItems: number;
  limit: number;
  currentPage: number;
  hasNext: boolean;
  hasPrevious: boolean;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: UserType;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: UserType;
}>;
